In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset= pd.read_csv('BankNote_Authentication.csv')

In [3]:
dataset.head

<bound method NDFrame.head of       variance  skewness  curtosis  entropy  class
0      3.62160   8.66610   -2.8073 -0.44699      0
1      4.54590   8.16740   -2.4586 -1.46210      0
2      3.86600  -2.63830    1.9242  0.10645      0
3      3.45660   9.52280   -4.0112 -3.59440      0
4      0.32924  -4.45520    4.5718 -0.98880      0
...        ...       ...       ...      ...    ...
1367   0.40614   1.34920   -1.4501 -0.55949      1
1368  -1.38870  -4.87730    6.4774  0.34179      1
1369  -3.75030 -13.45860   17.5932 -2.77710      1
1370  -3.56370  -8.38270   12.3930 -1.28230      1
1371  -2.54190  -0.65804    2.6842  1.19520      1

[1372 rows x 5 columns]>

In [4]:
dataset.head(20)

    variance  skewness  curtosis  entropy  class
0    3.62160    8.6661  -2.80730 -0.44699      0
1    4.54590    8.1674  -2.45860 -1.46210      0
2    3.86600   -2.6383   1.92420  0.10645      0
3    3.45660    9.5228  -4.01120 -3.59440      0
4    0.32924   -4.4552   4.57180 -0.98880      0
5    4.36840    9.6718  -3.96060 -3.16250      0
6    3.59120    3.0129   0.72888  0.56421      0
7    2.09220   -6.8100   8.46360 -0.60216      0
8    3.20320    5.7588  -0.75345 -0.61251      0
9    1.53560    9.1772  -2.27180 -0.73535      0
10   1.22470    8.7779  -2.21350 -0.80647      0
11   3.98990   -2.7066   2.39460  0.86291      0
12   1.89930    7.6625   0.15394 -3.11080      0
13  -1.57680   10.8430   2.54620 -2.93620      0
14   3.40400    8.7261  -2.99150 -0.57242      0
15   4.67650   -3.3895   3.48960  1.47710      0
16   2.67190    3.0646   0.37158  0.58619      0
17   0.80355    2.8473   4.34390  0.60170      0
18   1.44790   -4.8794   8.34280 -2.10860      0
19   5.24230   11.0272  -4.35300 -4.10130      0

In [5]:
x= dataset.iloc[:, :-1]
y= dataset.iloc[:,-1]

In [6]:
x.head

<bound method NDFrame.head of       variance  skewness  curtosis  entropy
0      3.62160   8.66610   -2.8073 -0.44699
1      4.54590   8.16740   -2.4586 -1.46210
2      3.86600  -2.63830    1.9242  0.10645
3      3.45660   9.52280   -4.0112 -3.59440
4      0.32924  -4.45520    4.5718 -0.98880
...        ...       ...       ...      ...
1367   0.40614   1.34920   -1.4501 -0.55949
1368  -1.38870  -4.87730    6.4774  0.34179
1369  -3.75030 -13.45860   17.5932 -2.77710
1370  -3.56370  -8.38270   12.3930 -1.28230
1371  -2.54190  -0.65804    2.6842  1.19520

[1372 rows x 4 columns]>

In [7]:
x.head(20)

    variance  skewness  curtosis  entropy
0    3.62160    8.6661  -2.80730 -0.44699
1    4.54590    8.1674  -2.45860 -1.46210
2    3.86600   -2.6383   1.92420  0.10645
3    3.45660    9.5228  -4.01120 -3.59440
4    0.32924   -4.4552   4.57180 -0.98880
5    4.36840    9.6718  -3.96060 -3.16250
6    3.59120    3.0129   0.72888  0.56421
7    2.09220   -6.8100   8.46360 -0.60216
8    3.20320    5.7588  -0.75345 -0.61251
9    1.53560    9.1772  -2.27180 -0.73535
10   1.22470    8.7779  -2.21350 -0.80647
11   3.98990   -2.7066   2.39460  0.86291
12   1.89930    7.6625   0.15394 -3.11080
13  -1.57680   10.8430   2.54620 -2.93620
14   3.40400    8.7261  -2.99150 -0.57242
15   4.67650   -3.3895   3.48960  1.47710
16   2.67190    3.0646   0.37158  0.58619
17   0.80355    2.8473   4.34390  0.60170
18   1.44790   -4.8794   8.34280 -2.10860
19   5.24230   11.0272  -4.35300 -4.10130

In [8]:
y.head(20)

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
Name: class, dtype: int64

In [9]:
y.head

<bound method NDFrame.head of 0       0
1       0
2       0
3       0
4       0
       ..
1367    1
1368    1
1369    1
1370    1
1371    1
Name: class, Length: 1372, dtype: int64>

In [10]:
##splitting dataset into Training set and Test set
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.3, random_state= 0)

In [11]:
print(x_test)

      variance   skewness  curtosis  entropy
1023  -1.77130 -10.766500  10.21840 -1.00430
642    5.13210  -0.031048   0.32616  1.11510
1196  -2.01490   3.687400  -1.93850 -3.89180
31     1.48840   3.627400   3.30800  0.48921
253    5.28680   3.257000  -1.37210  1.16680
...        ...        ...       ...      ...
986    0.84546   3.482600  -3.63070 -1.39610
271    5.39150   9.994600  -3.80810 -3.36420
1266  -1.43770  -1.432000   2.11440  0.42067
769   -0.89409   3.199100  -1.82190 -2.94520
634    6.82480   5.218700  -2.54250  0.54610

[412 rows x 4 columns]

In [12]:
##implement Random forest Classifier on training set
from sklearn.ensemble import RandomForestClassifier
classifier= RandomForestClassifier()
classifier.fit(x_train, y_train)

RandomForestClassifier()

In [13]:
## predict test set result
y_pred= classifier.predict(x_test)

In [14]:
##Check accuracy
from sklearn.metrics import accuracy_score
score= accuracy_score(y_test, y_pred)

In [15]:
print(score)

0.9902912621359223

In [17]:
## Creat a Pickle file using Serialization
import pickle
pickle_out= open("classifier.pkl","wb")
pickle.dump(classifier,pickle_out)
pickle_out.close()